language: java
install: true
jdk:
  - openjdk12
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoCoverageVerification
  - ./gradlew jacocoRootReport
after_success:
  - bash <(curl -s https://codecov.io/bash)